title: receipt-splitter
description: A local website to recognize and extract items in a receipt using a local OCR+LLM Model, to calculate cost breakdowns per pax with taxes.
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
