title: receipt-splitter
description: Website to upload, detect extract items in a receipt using PaddleOCRv5+Gemma3n Model, great for splitting bills
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
